// Initialize a new module from this template. Run once:
//   npm run init -- <new-module-id> [--title "Human Title"] [--org <github-owner>] [--author "Your Name"]
// Rewrites the template id/title across the repo, fills in your GitHub owner and author
// (auto-detected from git, or via flags), then deletes itself.
import { readdirSync, readFileSync, writeFileSync, rmSync } from 'node:fs';
import { join, extname, relative } from 'node:path';
import { ownerFromOrigin, authorName, isValidOwner } from './git-identity.ts';

const TOKEN_ID = 'pf2e-module-template';
const TOKEN_TITLE = 'PF2e Module Template';
const TOKEN_ORG = '<your-org>'; // placeholder GitHub owner in module.json url/manifest/download
const TOKEN_AUTHOR = '<your-name>'; // placeholder author name in module.json

const repo = process.cwd();
const args = process.argv.slice(2);

let newId: string | undefined;
let newTitle: string | undefined;
let newOrg: string | undefined;
let newAuthor: string | undefined;
for (let i = 0; i < args.length; i++) {
  const a = args[i];
  if (a === '--title') newTitle = args[++i];
  else if (a.startsWith('--title=')) newTitle = a.slice('--title='.length);
  else if (a === '--org') newOrg = args[++i];
  else if (a.startsWith('--org=')) newOrg = a.slice('--org='.length);
  else if (a === '--author') newAuthor = args[++i];
  else if (a.startsWith('--author=')) newAuthor = a.slice('--author='.length);
  else if (!a.startsWith('-') && !newId) newId = a;
}

if (!newId) {
  console.error('usage: npm run init -- <new-module-id> [--title "Human Title"] [--org <github-owner>] [--author "Your Name"]');
  process.exit(1);
}
if (!/^[a-z][a-z0-9-]*$/.test(newId)) {
  console.error(`invalid id "${newId}" — use lowercase letters, digits, and hyphens (e.g. pf2e-my-module)`);
  process.exit(1);
}
if (newOrg && !isValidOwner(newOrg)) {
  console.error(`invalid org "${newOrg}" — use a GitHub owner name (letters, digits, hyphens)`);
  process.exit(1);
}
newTitle ??= newId
  .split('-')
  .map((w) => (w === 'pf2e' ? 'PF2e' : w.charAt(0).toUpperCase() + w.slice(1)))
  .join(' ');

const resolvedOrg = newOrg ?? ownerFromOrigin(repo);
const resolvedAuthor = newAuthor ?? authorName(repo);

// Skip build output and binaries. NOT packs/: its _source JSON is text and must be rewritten
// (e.g. a macro that calls game.modules.get('<id>')); the built LevelDB under packs/<name> is
// gitignored and skipped by extension anyway, then regenerated by `npm run build`.
const SKIP_DIRS = new Set(['node_modules', '.git', 'dist', 'assets', '.claude']);
const TEXT_EXT = new Set(['.ts', '.mts', '.js', '.mjs', '.json', '.md', '.css', '.svelte', '.yml', '.yaml', '.html', '.hbs']);
const EXTRA_FILES = new Set(['LICENSE']);

function walk(dir: string, out: string[] = []): string[] {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.isSymbolicLink()) continue; // dev links (_foundry-data, etc.) point outside the repo
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (!SKIP_DIRS.has(entry.name)) walk(full, out);
    } else if (TEXT_EXT.has(extname(entry.name)) || EXTRA_FILES.has(entry.name)) {
      out.push(full);
    }
  }
  return out;
}

function stripTemplateBlock(md: string): string {
  return md.replace(/<!-- TEMPLATE:START -->[\s\S]*?<!-- TEMPLATE:END -->\n?/g, '');
}

const selfPath = join(repo, 'scripts', 'init.ts');
const lockPath = join(repo, 'package-lock.json');
const changelogPath = join(repo, 'CHANGELOG.md'); // the template's own history — removed below, not rewritten
let touched = 0;

for (const file of walk(repo)) {
  if (file === selfPath || file === lockPath || file === changelogPath) continue;
  const before = readFileSync(file, 'utf8');
  let after = before
    .replaceAll(TOKEN_ID, newId)
    .replaceAll(TOKEN_TITLE, newTitle)
    .replaceAll(TOKEN_TITLE.toUpperCase(), newTitle);

  // org/author placeholders are only fillable in module.json; elsewhere (setup.ts constants,
  // doc mentions) they're literal and must survive so setup.ts can still detect them.
  if (file.endsWith('module.json')) {
    if (resolvedOrg) after = after.replaceAll(TOKEN_ORG, resolvedOrg);
    if (resolvedAuthor) after = after.replaceAll(TOKEN_AUTHOR, resolvedAuthor);
  }

  if (file.endsWith('README.md')) after = stripTemplateBlock(after);
  if (file.endsWith('package.json')) after = after.replace(/^\s*"init": "node scripts\/init\.ts",\n/m, '');

  if (after !== before) {
    writeFileSync(file, after);
    touched++;
    console.log(`rewrote ${relative(repo, file)}`);
  }
}

if (touched === 0) {
  console.error('nothing to rewrite — already initialized?');
  process.exit(1);
}

rmSync(selfPath);
rmSync(lockPath, { force: true }); // stale name; regenerated by npm install
rmSync(changelogPath, { force: true }); // template history; the new module starts its own
console.log(`\n✓ initialized "${newId}" (${newTitle}). Removed scripts/init.ts and CHANGELOG.md.`);
console.log(`  owner: ${resolvedOrg ?? `(undetected — module.json still says "${TOKEN_ORG}"; set --org or edit it)`}`);
console.log(`  author: ${resolvedAuthor ?? `(undetected — module.json still says "${TOKEN_AUTHOR}"; set --author or edit it)`}`);
console.log('next: npm install && npm run build');
