// Initialize a new module from this template. Run once:
//   npm run init -- <new-module-id> [--title "Human Title"]
// Rewrites the template id/title across the repo, then deletes itself.
import { readdirSync, readFileSync, writeFileSync, statSync, rmSync } from 'node:fs';
import { join, extname, relative } from 'node:path';

const TOKEN_ID = 'pf2e-module-template';
const TOKEN_TITLE = 'PF2e Module Template';

const repo = process.cwd();
const args = process.argv.slice(2);

let newId;
let newTitle;
for (let i = 0; i < args.length; i++) {
  const a = args[i];
  if (a === '--title') newTitle = args[++i];
  else if (a.startsWith('--title=')) newTitle = a.slice('--title='.length);
  else if (!a.startsWith('-') && !newId) newId = a;
}

if (!newId) {
  console.error('usage: npm run init -- <new-module-id> [--title "Human Title"]');
  process.exit(1);
}
if (!/^[a-z][a-z0-9-]*$/.test(newId)) {
  console.error(`invalid id "${newId}" — use lowercase letters, digits, and hyphens (e.g. pf2e-my-module)`);
  process.exit(1);
}
newTitle ??= newId
  .split('-')
  .map((w) => (w === 'pf2e' ? 'PF2e' : w.charAt(0).toUpperCase() + w.slice(1)))
  .join(' ');

const SKIP_DIRS = new Set(['node_modules', '.git', 'dist', 'packs']);
const TEXT_EXT = new Set(['.ts', '.mts', '.js', '.mjs', '.json', '.md', '.css', '.svelte', '.yml', '.yaml', '.html', '.hbs']);
const EXTRA_FILES = new Set(['LICENSE']);

function walk(dir, out = []) {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      if (!SKIP_DIRS.has(entry)) walk(full, out);
    } else if (TEXT_EXT.has(extname(entry)) || EXTRA_FILES.has(entry)) {
      out.push(full);
    }
  }
  return out;
}

const selfPath = join(repo, 'scripts', 'init.mjs');
const lockPath = join(repo, 'package-lock.json');
let touched = 0;

for (const file of walk(repo)) {
  if (file === selfPath || file === lockPath) continue;
  const before = readFileSync(file, 'utf8');
  let after = before
    .replaceAll(TOKEN_ID, newId)
    .replaceAll(TOKEN_TITLE, newTitle)
    .replaceAll(TOKEN_TITLE.toUpperCase(), newTitle);

  if (file.endsWith('README.md')) after = stripTemplateBlock(after);
  if (file.endsWith('package.json')) after = after.replace(/^\s*"init": "node scripts\/init\.mjs",\n/m, '');

  if (after !== before) {
    writeFileSync(file, after);
    touched++;
    console.log(`rewrote ${relative(repo, file)}`);
  }
}

function stripTemplateBlock(md) {
  return md.replace(/<!-- TEMPLATE:START -->[\s\S]*?<!-- TEMPLATE:END -->\n?/g, '');
}

if (touched === 0) {
  console.error('nothing to rewrite — already initialized?');
  process.exit(1);
}

rmSync(selfPath);
rmSync(lockPath, { force: true }); // stale name; regenerated by npm install
console.log(`\n✓ initialized "${newId}" (${newTitle}). Removed scripts/init.mjs.`);
console.log('next: rm -rf .git && git init -b main && npm install && npm run build');
